# Generated by Django 5.2.8 on 2025-11-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_cliente_password_cliente_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
