# Generated by Django 5.2.8 on 2025-11-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('agendada', 'Agendada'), ('online', 'Online'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada'), ('reagendada', 'Reagendada'), ('finalizado', 'Finalizado'), ('atendido_reagendado', 'Atendido y Reagendado')], default='agendada', max_length=25)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mascotas.mascota')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='usuarios.medico')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='gestion_citas.sala')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
                'unique_together': {('sala', 'fecha', 'hora')},
            },
        ),
    ]
