# Generated by Django 5.2.8 on 2025-11-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='libre', max_length=25),
        ),
        migrations.AddField(
            model_name='sala',
            name='ubicación',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
