# Generated by Django 5.2.8 on 2025-11-27 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0002_sala_estado_sala_ubicación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='ubicación',
            new_name='ubicacion',
        ),
    ]
