# Generated by Django 5.2.8 on 2025-11-27 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0003_rename_ubicación_sala_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
