# Generated by Django 5.2.8 on 2025-11-27 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='gestion_citas.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion', models.CharField(blank=True, max_length=100, null=True)),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('prescrito_por', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_prescripcion', models.DateTimeField(auto_now_add=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='atencion_citas.historialclinico')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescripciones', to='atencion_citas.medicamento')),
            ],
            options={
                'unique_together': {('historial', 'medicamento', 'dosis', 'frecuencia')},
            },
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='medicamentos',
            field=models.ManyToManyField(related_name='historiales', through='atencion_citas.Prescripcion', to='atencion_citas.medicamento'),
        ),
    ]
